services:
  application:
    image: node:latest
    volumes:
      - ./application:/application
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - pg
  # database:
  #   image: mysql:8.1
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./database/data:/var/lib/mysql
  #     - ./database/config/my.cnf:/etc/mysql/my.cnf:ro
  #   env_file: ./database/.env
  pg:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg/init:/init
    env_file: ./pg/.env

