import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/providers/NextAuthProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={"text-gray-800 bg-gray-100 font-sans leading-normal tracking-normal"}
      >
        <div className="min-h-screen flex flex-col h-full">
          <NextAuthProvider>
            <Header />
            <main className="container mx-auto overflow-hidden flex-1 px-4 pt-14">
              {children}
            </main>
            <Footer />
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
